{
 "title": "Traces Panel",
 "tags": [
  "demo",
  "visualization"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "traceId", "label": "Trace ID" },
   {
    "name": "minDuration",
    "label": "Min duration",
    "query": "0ms,1ms,5ms,10ms,20ms,50ms,100ms"
   }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Traces",
   "type": "table",
   "gridPos": { "h": 22, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "filters": [
      { "id": "e4879c25", "operator": "=", "scope": "span" },
      {
       "id": "service-name",
       "isCustomValue": false,
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": [ "hyliquid-orderbook" ],
       "valueType": "string"
      },
      {
       "id": "min-duration",
       "operator": ">",
       "tag": "duration",
       "value": "1ms",
       "valueType": "duration"
      }
     ],
     "limit": 20,
     "metricsQueryType": "range",
     "query": "{resource.service.name=\"hyliquid-orderbook\" && duration>$minDuration}",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Traces panel",
   "type": "traces",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "limit": 20,
     "metricsQueryType": "range",
     "query": "${traceId}",
     "scenarioId": "trace",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Spans",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {
     "filters": [
      { "id": "19da16a1", "operator": "=", "scope": "span" }
     ],
     "limit": 20,
     "metricsQueryType": "range",
     "query": "{trace:id=\"$traceId\"} | select(span:name)",
     "spss": 30,
     "tableType": "spans"
    }
   ]
  }
 ]
}